function htmenu
%
%  Name: htmenu
% 
%  Usage: htmenu
% 
%  Description:
%     Initializes help and tasks menus
%

%  Version SWD970804
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This matlab source code was originally     %
% developed as part of "DIAMOND" at          %
% Los Alamos National Laboratory. It may     %
% be copied, modified, and distributed in    %
% any form, provided:                        %
%  a) This notice accompanies the files and  %
%     appears near the top of all source     %
%     code files.                            %
%  b) No payment or commercial services are  %
%     received in exchange for the code.     %
%                                            %
% Original copyright is reserved by the      %
% Regents of the University of California,   %
% in addition to Scott W. Doebling, Phillip  %
% J. Cornwell, Erik G. Straser, and Charles  %
% R. Farrar.                                 %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%

global HANDLES

%===================================
% Task Menus
%===================================
HANDLES.hmmenu{11}(1) = uimenu(HANDLES.hfigdmnd,'Label','Tasks','enable','on');
HANDLES.hmmenu{12}(1)=  uimenu(HANDLES.hmmenu{11}(1),'Label','Modal Analysis',...
	'checked','on',...
	'callback', [ ...
	'hideallbtns,', ...
   'vismen = 1; menuvis,',...	
   'set(HANDLES.hmmenu{12}(1),''checked'',''on''),',...
	'set(HANDLES.hmmenu{13}(1),''checked'',''off''),',...
	'set(HANDLES.hmmenu{14}(1),''checked'',''off''),',...
	'set(HANDLES.hmmenu{15}(1),''checked'',''off''),',...
	'set(HANDLES.hfigdmnd,''name'',''Diamond:  Modal Analysis'');']);	
HANDLES.hmmenu{13}(1)=   uimenu(HANDLES.hmmenu{11}(1),'Label','Damage Identification',...
   'callback', [ ...
	'hideallbtns,', ...
	'vismen = 2; menuvis,',...	
   'set(HANDLES.hmmenu{12}(1),''checked'',''off''),',...
	'set(HANDLES.hmmenu{13}(1),''checked'',''on''),',...
	'set(HANDLES.hmmenu{14}(1),''checked'',''off''),',...
	'set(HANDLES.hmmenu{15}(1),''checked'',''off''),',...
	'set(HANDLES.hfigdmnd,''name'',''Diamond:  Damage Identification'');']);
HANDLES.hmmenu{14}(1)=   uimenu(HANDLES.hmmenu{11}(1),'Label','Model Correlation','callback', [ ...
	'hideallbtns,', ...
   'vismen = 3; menuvis,',...	
   'set(HANDLES.hmmenu{12}(1),''checked'',''off''),',...
	'set(HANDLES.hmmenu{13}(1),''checked'',''off''),',...
	'set(HANDLES.hmmenu{14}(1),''checked'',''on''),',...
	'set(HANDLES.hmmenu{15}(1),''checked'',''off''),',...
   'set(HANDLES.hfigdmnd,''name'',''Diamond:  Model Correlation'');']);

HANDLES.hmmenu{15}(1)=   uimenu(HANDLES.hmmenu{11}(1),'Label','Test Simulation','callback', [ ...
	'hideallbtns,', ...
   'vismen = 4; menuvis,',...	
   'set(HANDLES.hmmenu{12}(1),''checked'',''off''),',...
	'set(HANDLES.hmmenu{13}(1),''checked'',''off''),',...
	'set(HANDLES.hmmenu{14}(1),''checked'',''off''),',...
	'set(HANDLES.hmmenu{15}(1),''checked'',''on''),',...
	'set(HANDLES.hfigdmnd,''name'',''Diamond:  Test Simulation'');']);

%HANDLES.hmmenu{15}(1)=  uimenu(HANDLES.hmmenu{11}(1),'Label','Test Simulation',...
%	'callback','errordlg(''Test Simulator not Installed'')');	


%=======================================
% Help menu
%========================================
  HANDLES.hmmenu{16}(1)=uimenu(HANDLES.hfigdmnd,'Label','Help','enable','on');
  uimenu(HANDLES.hmmenu{16}(1),'Label','Index','callback','disp(''This item is not operational yet'')','enable','off')
  
return